t1:
	gopatch -p patch/t1.patch patch_test.go

t2:
	gopatch -p patch/t2.patch patch_test.go

t3:
	gopatch -p patch/t3.patch patch_test.go

t4:
	gopatch -p patch/t4.patch patch_test.go

t5:
	gopatch -p patch/t5.patch patch_test.go
