run-server:
	go run main/server.go

run-http-1:
	go run main/client.go -version 1

run-http-2:
	go run main/client.go -version 2

run-h2connServer:
	go run main/h2server.go

run-h2connClient:
	go run main/h2client.go