gen:
	go run main.go --pkg_name=github.com/LiveAlone/GoLibSourceAnalyse/utils --pkg_path=/Users/zyb/workspace/person/GitHub/GoLibSourceAnalyse/utils --depth=2 --dot_file_path=godag.dot

png:
	dot -Tpng godag.dot > godag.png
