help:
	go run main.go -h

helpD:
	go run main.go -D -h

model:
	go run main.go model -d dest

build:
	go build

api-brick:
	go run main.go api -p brick -a 315713 -d dest

api-hxxmis:
	go run main.go api -p hxxmis -a 643396 -d dest

api-unit:
	go run main.go api -p unit -a 670477 -d dest